{% set name = "pyfmmlib" %}
{% set version = "2019.1.1" %}
{% set sha256 = "2af271df581d5fc76a5721aa229e73af93ad2c8fb47bcc316baa62e06d1ddad7" %}
{% set build_number = 1 %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: {{ build_number }}
  skip: True  # [win]

requirements:
  build:
    - {{ compiler('fortran') }}
    - {{ compiler('c') }}
  host:
    - python
    - setuptools
    - numpy
    - mako
  run:
    - python
    - {{ pin_compatible('numpy') }}

test:
    requires:
        - pytest
    imports:
        - {{ name }}
    source_files:
        - test
    commands:
        - cd test && python -m pytest

about:
    home: https://github.com/inducer/pyfmmlib
    license: MIT/BSD-3-Clause
    license_file: README.rst
    summary: 'Python wrappers for FMMLIB2D and FMMLIB3D'

    dev_url: https://github.com/inducer/pyfmmlib

extra:
    recipe-maintainers:
    - inducer
