{% set name = "pyfmmlib" %}
{% set version = "2019.1.5" %}
{% set sha256 = "b47e61be41474425852dfa2ad00757fd1327b76869d518c10c9578a522ba46d8" %}
{% set build_number = 0 %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: {{ build_number }}

requirements:
  build:
    - {{ compiler('fortran') }}  # [not win]
    - {{ compiler('c') }}        # [not win]
    - {{ compiler('m2w64_c') }}  # [win]
    - {{ compiler('m2w64_fortran') }}  # [win]
  host:
    - python
    - setuptools
    - numpy
    - mako
  run:
    - python
    - {{ pin_compatible('numpy') }}

test:
  requires:
    - pytest
  imports:
    - {{ name }}
  source_files:
    - test
  commands:
    - cd test && python -m pytest

about:
  home: https://github.com/inducer/pyfmmlib
  license: MIT/BSD-3-Clause
  license_file: README.rst
  summary: 'Python wrappers for FMMLIB2D and FMMLIB3D'
  dev_url: https://github.com/inducer/pyfmmlib

extra:
  recipe-maintainers:
    - inducer
    - isuruf
