{% set name = "pyfmmlib" %}
{% set version = "2024.1.1" %}
{% set sha256 = "1c48575c133499b6ec0130d866694bccbda52c842f2fb9f9277b1ccfc19323ac" %}
{% set build_number = 2 %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: {{ build_number }}

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
    - {{ compiler('fortran') }}  # [not win]
    - {{ compiler('c') }}        # [not win]
    - {{ stdlib("c") }}          # [not win]
    - {{ stdlib("c") }}          # [not win]
    - {{ compiler('m2w64_c') }}  # [win]
    - {{ stdlib("m2w64_c") }}    # [win]
    - {{ stdlib("m2w64_c") }}    # [win]
    - {{ compiler('m2w64_fortran') }}  # [win]
    - llvm-openmp   # [osx]
    - libgomp       # [linux]
    - meson-python                           # [build_platform != target_platform]
    - ninja                                  # [build_platform != target_platform]
    - pkg-config                             # [build_platform != target_platform]
  host:
    - python
    - pip
    - numpy
    - mako
    - meson-python
    - ninja
    - pkg-config
    - python-build
  run:
    - python

test:
  requires:
    - pytest
    - scipy
  imports:
    - {{ name }}
  source_files:
    - test
  commands:
    - cd test && python -m pytest

about:
  home: https://github.com/inducer/pyfmmlib
  license: MIT AND BSD-3-Clause
  license_file: README.rst
  summary: Python wrappers for FMMLIB2D and FMMLIB3D
  dev_url: https://github.com/inducer/pyfmmlib

extra:
  recipe-maintainers:
    - inducer
    - isuruf
    - matthiasdiener
