{% set name = "pyfmmlib" %}
{% set version = "2018.1.3" %}
{% set sha256 = "99f242210f235d80bc828f0fa64d63fad003aa1f568e6702450adb56bdd65f3c" %}
{% set build_number = 0 %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: {{ build_number }}
  skip: True  # [win]

requirements:
  build:
    - {{ compiler('fortran') }}
    - {{ compiler('c') }}
    - toolchain3
  host:
    - python
    - setuptools
    - numpy
    - mako
  run:
    - python
    - numpy
    - libgfortran >=3.0.1  # [osx]

test:
    requires:
        - pytest
    imports:
        - {{ name }}
    source_files:
        - test
    commands:
        - cd test && python -m pytest

about:
    home: https://github.com/inducer/pyfmmlib
    license: MIT/BSD-3-Clause
    license_file: README.rst
    summary: 'Python wrappers for FMMLIB2D and FMMLIB3D'

    dev_url: https://github.com/inducer/pyfmmlib

extra:
    recipe-maintainers:
    - inducer
